filmcat/config/routes.rb
Filmcat::Application.routes.draw do

  resources :users, :only => [:index, :destroy]

  get "omniauth_callbacks/facebook"
  get "omniauth_callbacks/vkontakte"
  get "comments/new"
  get "films/index"
  devise_for :users
  root 'films#index'
  resources :users, :films, :comments

  get '/new' => 'users#new'
  resources :films, only: :show
  post 'films/like' => 'films#like'

end

filmcat/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :film
	belongs_to :user
end

filmcat/app/models/film.rb
class Film < ActiveRecord::Base
	has_many :comments
	has_many :film_joins
	has_many :users, through: :film_joins
end

filmcat/app/models/film_join.rb
class FilmJoin < ActiveRecord::Base
end

filmcat/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook,:vkontakte]

  has_many :comments
  has_many :film_joins
  has_many :films, through: :film_joins

  def self.find_for_facebook_oauth access_token
    if user = User.where(:url => access_token.info.urls.Facebook).first
      user
    else 
      User.create!(:provider => access_token.provider, :url => access_token.info.urls.Facebook, :username => access_token.extra.raw_info.name, :nickname => access_token.extra.raw_info.username, :email => access_token.extra.raw_info.email, :password => Devise.friendly_token[0,20]) 
    end
  end

  def self.find_for_vkontakte_oauth access_token
    if user = User.where(:url => access_token.info.urls.Vkontakte).first
      user
    else 
      User.create!(:provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain, :email => access_token.extra.raw_info.domain+'@user.vk.com', :password => Devise.friendly_token[0,20]) 
    end
  end
end

filmcat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	users_path
  end

  def after_sign_out_path_for(resource_or_scope)
  	users_path
	#request.referrer
  end

end

filmcat/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@comment = Comment.new(params.require(:comment).permit(:text, :film_id))
  	@comment.user_id = current_user.id
  	@comment.save
  	#redirect_to film_path(@comment[:film_id])
  	redirect_to films_path(@film)
  end
end

filmcat/app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
  	@films = Film.all
  end

  def show
  	@film = Film.find(params[:id])
  	@comment = Comment.new()
  end

  def like
  	@film = Film.find(params[:id])
  	@film.rating += 1
  	@film.save
  	redirect_to film_path(@film)
  end
end

filmcat/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
  	end
	end
	
  def vkontakte
  	@user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

filmcat/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all 
	end

	def new
		@user = User.new()
	end

	def show
		#@user = User.find(params[:user])
	end

	def create
		
	end

	def destroy
	end
end

filmcat/app/helpers/comments_helper.rb
module CommentsHelper
end

filmcat/app/helpers/films_helper.rb
module FilmsHelper
end

filmcat/app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

filmcat/app/helpers/users_helper.rb
module UsersHelper
end

filmcat/app/views/films/index.html.erb
<br/>
<br/>
<br/>
<% @films.each do |film| %>
<p><%= link_to film.name, film_path(film) %></p><br/>
<%= image_tag(film.url_img, height: '271', width: '180', alt: '') %>
<% end %>

filmcat/app/views/films/show.html.erb
<%= @film.name %><br/>
<%= image_tag(@film.url_img,  height: '542', width: '360', alt: '') %><br/>
<%= image_submit_tag('http://media.karaspartyideas.com/media/plugins/floating-social-media-links/img/like.png', controller: 'films',action: 'like',height: '20', width: '50', alt: 'Like') %>
<%= form_for @film, :url => like_film_path(@film), :action => 'like' do%>
<%= image_submit_tag('http://media.karaspartyideas.com/media/plugins/floating-social-media-links/img/like.png', controller: 'films',action: 'like',height: '20', width: '50', :alt => 'Like') %>
<% end %>
<%= @film.rating %><br/>

<p><%= link_to 'All Films', films_path %></p>
<%= @film.release_date %><br/>
<%= @film.description %><br/>
<p>Comments</p>
<% @film.comments.each do |comment| %>
<%= comment.text %>
<%= comment.created_at %>
<%= comment.user.email %><br/>
<% end %>
<%= simple_form_for @comment, :url => comments_path do |f| %>
<%= f.input :text, label: 'Comment' %><br/>
<%= f.input :film_id,:as => :hidden, input_html: {value: @film.id} %>
<%= f.button :submit %>
<% end %>

filmcat/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Filmcat"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href=films_path) Filmcat
          .container.nav-collapse
            %ul.nav
              %li= link_to "Users", users_path

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            //%h3 Sidebar
            //%ul.nav.nav-list
            //  %li.nav-header Sidebar
            //  %li= link_to "Link 1", "/path1"
    
      %footer
        %p &copy; Company 2014

filmcat/app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :email
  = f.input :encrypted_password
  = f.input :reset_password_token
  = f.input :reset_password_sent_at
  = f.input :remember_created_at
  = f.input :current_sign_in_at
  = f.input :last_sign_in_at
  = f.input :current_sign_in_ip
  = f.input :last_sign_in_ip
  = f.input :password
  = f.input :username
  = f.input :nickname
  = f.input :provider
  = f.input :url
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

filmcat/app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

filmcat/app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:encrypted_password)
      %th= model_class.human_attribute_name(:reset_password_token)
      %th= model_class.human_attribute_name(:reset_password_sent_at)
      %th= model_class.human_attribute_name(:remember_created_at)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:current_sign_in_ip)
      %th= model_class.human_attribute_name(:last_sign_in_ip)
      %th= model_class.human_attribute_name(:password)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:nickname)
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:url)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.email
        %td= user.encrypted_password
        %td= user.reset_password_token
        %td= user.reset_password_sent_at
        %td= user.remember_created_at
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td= user.password
        %td= user.username
        %td= user.nickname
        %td= user.provider
        %td= user.url
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

filmcat/app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

filmcat/app/views/users/show.html.erb
<p>users#show</p>

filmcat/app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:password) + ':'
  %br
  = @user.password
%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:nickname) + ':'
  %br
  = @user.nickname
%p
  %strong= model_class.human_attribute_name(:provider) + ':'
  %br
  = @user.provider
%p
  %strong= model_class.human_attribute_name(:url) + ':'
  %br
  = @user.url

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'