films/config/routes.rb
Films::Application.routes.draw do
  get "genres/show"
  get "comment/create"
  get "video/new"
  get "video/create"
    
  devise_for :users
  
  root to: "home#index"

  resources :comment # oni dolzhni byt v mozhestvennom chisle

  resources :genres

  resources :videos do
    member do
      post :like
      post :favorite
      patch :favorite
      get :genre
      get :sort
      get :watched
      post :premiere
      patch :premiere
      get :premiere_list
    end
  end

  resources :locales

  

end

films/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Films" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body style="background-color:#333333">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to t(:app), root_path, class: "brand"%>

          <div class="container nav-collapse">
            <ul class="nav">
              <% if current_user %>
                <li><a> <%= t :Hello, user: current_user.email %></a></li>
                <li>
                  <%= link_to t('Logout'), destroy_user_session_path, :method => :delete %>
                </li>
                <% if current_user.admin? %>
                <li>
                  <%= link_to t('New_video'), new_video_path %>
                </li>
                <% end %>
                <li>
                  <%= link_to t('Watched_Films'), watched_video_path(current_user) %>
                </li>
                <li>
                  <%= link_to t('Premiere_Films'), premiere_list_video_path(current_user) %>
                </li>
              <% else %>
                <li>
                  <%= link_to t('Register'), new_user_registration_path  %>
                </li>
                <li>
                  <%= link_to t('Sign_in'), new_user_session_path  %>
                </li>
              <% end %>            
            </ul>
            <ul class="nav navbar-right">
              <li><%= link_to "en", "#{locales_path}?locale=en" %></li>
              <li><%= link_to "ru", "#{locales_path}?locale=ru" %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
  
    <div class="container-fluid" style="padding-top: 40px;"> 
        <%= bootstrap_flash %>
        <%= yield %> 
    </div> <!-- /container -->

  </body>
</html>