films/config/routes.rb
Films::Application.routes.draw do
  get "genres/show"
  get "comment/create"
  get "video/new"
  get "video/create"
    
  devise_for :users
  
  root to: "home#index"

  resources :comment # oni dolzhni byt v mozhestvennom chisle

  resources :genres

  resources :videos do
    member do
      post :like
      post :favorite
      patch :favorite
      get :genre
      get :sort
      get :watched
      post :premiere
      patch :premiere
      get :premiere_list
    end
  end

  resources :locales

  

end

films/app/models/video.rb
class Video < ActiveRecord::Base
	has_many :comments
	has_many :likes

	has_many :video_joins
	has_many :users, through: :video_joins
	
	has_many :genre_videos
	has_many :genres, through: :genre_videos

	has_many :premiere_videos

	default_scope { order(:name) }
	accepts_nested_attributes_for :genres, :allow_destroy => true

	has_attached_file :image
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

films/app/controllers/video_controller.rb
class VideoController < ApplicationController
  def new
  	@video = Video.new()
    @genre_video = GenreVideo.new
  end

  def create
  	@video = Video.new(params.require(:video).permit([:name, :description, :url_img, :url_video, :release_date]))
    @video.rating = 0
    params.require(:genre).permit(:id).each do |genre|
      GenreVideo.create(:genre_id => genre, :video_id => @video.id)
    end
  	@video.save
  	redirect_to root_path
  end

  def show
  	@film = Video.find(params[:id])

  	@comment = Comment.new()

    @video_genre = @film.genres

    @video_join = VideoJoin.where(user_id: current_user.id, video_id: params[:id]).first    
    if @video_join.nil?
      @video_join = VideoJoin.new
    else
      @video_join.favorite = true
    end

    @premiere_video = PremiereVideo.where(user_id: current_user.id, video_id: params[:id]).first    
    @premiere_video = PremiereVideo.new if @premiere_video.nil?

  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to root_path
  end

  def update
    @video = Video.find(params[:id])
    
    @video.update_attributes(params.require(:video).permit([:name, :description, :url_img, :url_video, :release_date, :genre]))
    #@video.genres.update_attributes(params.require(:genre).permit(:id))
    #params.require(:genre).permit(:id).each do |id|
    #  @video.genres.create(:genre_id => id, :video_id => @video.id)
    #end
    redirect_to video_path(@video)
  end

  def edit
    @video = Video.find(params[:id])
    @genre_video = GenreVideo.new
  end

  def like
    @film = Video.find(params[:id])
    @film.rating += 1
    @film.save
    redirect_to video_path(@film.id)
  end

  def favorite
    @id = params.require(:video_join).permit([:video_id])
    @video_join = VideoJoin.where(user_id: current_user.id, video_id: params[:id]).first    
    if @video_join.nil?      
      @film_join = VideoJoin.create(params.require(:video_join).permit([:user_id, :video_id]))
    else      
      @video_join.destroy
    end
    redirect_to video_path(@id)
  end

  def watched
    @videos = current_user.videos
  end

  def genre
    @genre = Genre.find(params[:id])
    @videos = @genre.videos.all
  end

  def premiere
    @premiere_video = PremiereVideo.where(user_id: current_user.id, video_id: params[:id]).first
    if @premiere_video.nil?
      PremiereVideo.create(params.require(:premiere_video).permit([:user_id, :video_id]))
    else
      @premiere_video.destroy
    end
    redirect_to video_path(params[:id])
  end

  def premiere_list
    @ids = PremiereVideo.where(user_id: current_user.id)
    @videos = Array.new
    @ids.each{|id| @videos.push(Video.find(id.video_id))}
  end
  
end

films/app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    if current_user and current_user.admin?
    	@video = Video.new()
      @video.genres.build
    else
      flash[:alert] = "You're not an admin! Get out!"
    end
  end

  def create
  	@video = Video.new(video_params)
    @video.rating = 0
  	@video.save
  	redirect_to root_path
  end

  def edit
    if current_user and current_user.admin?
      @video = Video.find(params[:id])
      @video.genres.build
    else
      flash[:alert] = "You're not an admin! Get out!"
    end
  end

  def update
    @video = Video.find(params[:id])    
    @video.update_attributes(video_params)
    redirect_to video_path(@video)
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to root_path
  end

  def show
  	@film = Video.find(params[:id])
  	@comment = Comment.new()

    if current_user
      @video_join = VideoJoin.where(user_id: current_user.id, video_id: params[:id]).first    
      if @video_join.nil?
        @video_join = VideoJoin.new
      else
        @video_join.favorite = true
      end
      @premiere_video = PremiereVideo.where(user_id: current_user.id, video_id: params[:id]).first    
      @premiere_video = PremiereVideo.new if @premiere_video.nil?
    end
  end

  def like
    @film = Video.find(params[:id])
    @like = Like.where(user_id: current_user.id, video_id: @film.id).first
    if @like.nil?
      @film.rating += 1
      Like.create(user_id: current_user.id, video_id: @film.id)      
    else
      flash[:alert] = 'You can rate one time'      
    end
    @film.save
    redirect_to video_path(@film.id)
  end

  def favorite
    @id = params.require(:video_join).permit([:video_id])
    @video_join = VideoJoin.where(user_id: current_user.id, video_id: params[:id]).first    
    if @video_join.nil?      
      @film_join = VideoJoin.create(params.require(:video_join).permit([:user_id, :video_id]))
    else      
      @video_join.destroy
    end
    redirect_to video_path(@id)
  end

  def watched

    @videos = current_user.videos
  end

  def premiere
    @premiere_video = PremiereVideo.where(user_id: current_user.id, video_id: params[:id]).first
    if @premiere_video.nil?
      PremiereVideo.create(params.require(:premiere_video).permit([:user_id, :video_id]))
    else
      @premiere_video.destroy
    end
    redirect_to video_path(params[:id])
  end

  def premiere_list
    @ids = PremiereVideo.where(user_id: current_user.id)
    @videos = Array.new
    @ids.each{|id| @videos.push(Video.find(id.video_id))}
  end

  private   

  def video_params
    params.require(:video).permit(:name, :description, :url_img, :url_video, :release_date, :image, :genre_ids => [])
  end
end

films/app/helpers/video_helper.rb
module VideoHelper
end

films/app/views/videos/_form.html.erb
    <div class="form-group">
      Name <br/> <%= f.text_field :name, placeholder: "Name", class: "form-control" %><br/>    
    </div>
    <div class="form-group">
      Description <br/> <%= f.text_area :description, placeholder: "Description", class: "form-control" %><br/> 
    </div>
    <div class="form-group">
      Picture <br/> <%= f.text_field :url_img, placeholder: "url_image", class: "form-control" %><br/>
      <%= f.file_field :image %> 
    </div>
    <div class="form-group">
      Video <br/> <%= f.text_field :url_video, placeholder: "url_video", class: "form-control" %><br/> 
    </div>
    <div class="form-group">
      Release date<br/> <%= f.text_field :release_date, placeholder: "release_date", class: "form-control" %><br/> 
    </div>
    <div class="form-group">
      Genre<br/> <%= f.collection_select :genre_ids, Genre.all, :id, :genre, {}, {:multiple => true} %>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>

films/app/views/videos/_video.html.erb
<br /><%= link_to video.name, video_path(video) %>
<% if video.image? %>
	<br /><%= link_to image_tag(video.image.url, height: '271', width: '180', alt: '', class: "img-rounded"), video_path(video)  %>
<% else %>
	<br /><%= link_to image_tag(video.url_img, height: '271', width: '180', alt: '', class: "img-rounded"), video_path(video) %>
<% end %>

films/app/views/videos/edit.html.erb
<div class="container" style="margin-left: 100px; color:#eeeeee">
  <div class="row">
    <div class=" col-lg-4 ">
    	<% if current_user and current_user.admin? %> 
  		<%= form_for @video, html: {:multipart => true}, url: video_path do |f| %>
  		<div class="form-group">
      	<%= t 'Name' %> <br/> <%= f.text_field :name, placeholder: "Name", class: "form-control" %><br/>    
	    </div>
	    <div class="form-group">
	      <%= t 'Description' %> <br/> <%= f.text_area :description, placeholder: "Description", class: "form-control" %><br/> 
	    </div>
	    <div class="form-group">
	      <%= t 'Picture' %> <br/> <%= f.text_field :url_img, placeholder: "url_image", class: "form-control" %><br/>
	      <%= f.file_field :image %> 
	    </div>
	    <div class="form-group">
	      <%= t 'Video' %> <br/> <%= f.text_field :url_video, placeholder: "url_video", class: "form-control" %><br/> 
	    </div>
	    <div class="form-group">
	      <%= t 'Release date' %><br/> <%= f.text_field :release_date, placeholder: "release_date", class: "form-control" %><br/> 
	    </div>
	    <div class="form-group">
	      <%= t 'Genre' %><br/> <%= f.collection_select :genre_ids, Genre.all, :id, :genre, {}, {:multiple => true} %>
	    </div>
	    <button type="submit" class="btn btn-default">Submit</button>
  		<% end %>
			<% end %>      
    </div> <!-- /col-lg-4 -->
  </div> <!-- /row -->
</div><!-- /container -->

films/app/views/videos/new.html.erb
<div class="container" style="margin-left: 100px; color:#eeeeee">
  <div class="row">
    <div class=" col-lg-4 ">
    	<% if current_user and current_user.admin? %> 
  		<%= form_for @video, html: {:multipart => true}, url: videos_path do |f| %>
      <div class="form-group">
	      <%= t 'Name' %> <br/> <%= f.text_field :name, placeholder: "Name", class: "form-control" %><br/>    
	    </div>
	    <div class="form-group">
	      <%= t 'Description' %> <br/> <%= f.text_area :description, placeholder: "Description", class: "form-control" %><br/> 
	    </div>
	    <div class="form-group">
	      <%= t 'Picture' %> <br/> <%= f.text_field :url_img, placeholder: "url_image", class: "form-control" %><br/>
	      <%= f.file_field :image %> 
	    </div>
	    <div class="form-group">
	      <%= t 'Video' %> <br/> <%= f.text_field :url_video, placeholder: "url_video", class: "form-control" %><br/> 
	    </div>
	    <div class="form-group">
	      <%= t 'Release date' %><br/> <%= f.text_field :release_date, placeholder: "release_date", class: "form-control" %><br/> 
	    </div>
	    <div class="form-group">
	      <%= t 'Genre' %><br/> <%= f.collection_select :genre_ids, Genre.all, :id, :genre, {}, {:multiple => true} %>
	    </div>
	    <button type="submit" class="btn btn-default">Submit</button>
      <% end %>
			<% end %>
    </div> <!-- /col-lg-4 -->
  </div> <!-- /row -->
</div><!-- /container -->

films/app/views/videos/premiere_list.html.erb
<h1><%= t 'Premiere' %></h1>
<% @videos.each do |video| %>
<div class="span4">
<%= link_to video.name, video_path(video) %><br/>
<%= image_tag(video.url_img, height: '271', width: '180', alt: '', class: "img-rounded") %><br/>
</div>
<% end %>

films/app/views/videos/show.html.erb
<div class="container" style="margin-left: 100px;">
	<div class="row">
		<div class=" col-lg-6 ">
			<h1 style="color:#eeeeee"><%= @film.name %><br/></h1>
			<div class="lead" style="color:#eeeeee">
				<%= t 'Genre' %>: <% @film.genres.each do |genre| %>
				<%= link_to genre.genre, genre_path(genre.id) %><% end %><br/>
			<%= t 'Release' %>: <%= @film.release_date.strftime("%Y-%b-%d") %><br/>			
			</div>
			
			<% if @film.image? %>
				<%= image_tag @film.image.url %><br />
			<% else %>
				<%= image_tag(@film.url_img,  height: '542', width: '360', alt: '') %><br/>
			<% end %>
			<span style="color:#eeeeee">
				<%= @film.description %><br/>
				<% if current_user %>
					<%= form_for @film, :url => like_video_path(@film), :method => :post do |f|%>
					<%= image_submit_tag('http://www.schneiderpr.com/blog/wp-content/uploads/2012/04/like-button.png', height: '20', width: '50', :alt => 'Like') %>
					<% end %>
				<% end %>
				<%= t :Rating, param: '' %> <%= @film.rating %><br/>
			</span>

			<%= link_to t('All_Films'), root_path %>
		<% if current_user %>
			<% if current_user.admin? %>
				<%= link_to t('Delete'), video_path, :method => :delete %>
				<%= link_to t('Edit'), edit_video_path %>
			<% end %>

		
			<% if @film.release_date < Time.now %>
				<%= form_for @video_join, :url => favorite_video_path do |f| %>	
					<% if @video_join.favorite == true %>
						<%= f.hidden_field :video_id, value: @film.id %>
						<%= f.hidden_field :user_id, value: current_user.id %>
						<%= f.hidden_field :favorite, value: 'true' %>
						<%= image_submit_tag('watched.png', height: '40', width: '100', :alt => 'Like') %>
					<% else %>
						<%= f.hidden_field :video_id, value: @film.id %>
						<%= f.hidden_field :user_id, value: current_user.id %>
						<%= f.hidden_field :favorite, value: 'false' %>
						<%= image_submit_tag('watched-2.png', height: '40', width: '100', :alt => 'Like') %>
					<% end %>
				<% end %>
			<% else %>
				<%= form_for @premiere_video, :url => premiere_video_path do |f| %>
					<% if @premiere_video.user_id == current_user.id %>
						<%= f.hidden_field :video_id, value: @film.id %>
						<%= f.hidden_field :user_id, value: current_user.id %>
						<%= image_submit_tag('Unsubscribe.png', height: '40', width: '100', :alt => 'Premiere') %>	
					<% else %>
						<%= f.hidden_field :video_id, value: @film.id %>
						<%= f.hidden_field :user_id, value: current_user.id %>
						<%= image_submit_tag('Subscribe.png', height: '40', width: '100', :alt => 'Premiere') %>
					<% end %>
				<% end %>
			<% end %>
		<% end %>
		</div>

		<div class="col-xs-12 col-md-8">
	  	<iframe width="560" height="315" src="<%= @film.url_video %>" frameborder="0" allowfullscreen></iframe>
	  	<div class="well">
				<h4><%= t 'Comments' %></h4>
				<% @film.comments.each do |comment| %>
				<h4><%= simple_format comment.text %></h4>
				<%= comment.created_at.strftime("%Y-%b-%d") %>
				<%= comment.user.email %><br/>
				<% end %>

				<% if current_user %>
					<%= form_for @comment, :url => comment_index_path do |f| %>
					<%= f.text_area :text, class: "form-control", placeholder: 'Comment' %><br/>
					<%= f.hidden_field :video_id, value: @film.id %>
					<%= f.button :submit, class: 'btn btn-default'%>
					<% end %>
				<% end %>
			</div><!-- /well -->
		</div>

	</div> <!-- /row -->
</div><!-- /container -->

films/app/views/videos/watched.html.erb
<h1><%= t 'Watched Films' %></h1>
<% @videos.each do |video| %>
<div class="span4">
<%= link_to video.name, video_path(video) %><br/>
<%= image_tag(video.url_img, height: '271', width: '180', alt: '', class: "img-rounded") %><br/>
</div>
<% end %>